version: "3"
services:
    company:
        image: company:latest
        build: 
            context: ..\src\api
        ports:
            - "8000:80"
        depends_on:
            - db
        environment: 
            ASPNETCORE_ENVIRONMENT: "Production"
            ConnectionString: "Server=db;Database=master;App=CompanyAPI;User Id=SA;Password=Pass@123;"
            Jwt__Issuer: "Company"
            Jwt__Key: "0d734a1dc94fe5a914185f45197ea846"
            Auth__Username: "superadmin"
            Auth__Password: "P@ss123"
    db:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        environment:
            SA_PASSWORD: "Pass@123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"